name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install multilibs
      run: sudo apt-get install gcc-multilib gcc-mingw-w64

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: make test

    - name: Build Artifacts
      run: make artifacts

    - uses: actions/upload-artifact@v2
      with:
        name: linux-x64
        path: artifacts-linux-x64

    - uses: actions/upload-artifact@v2
      with:
        name: windows-x64
        path: artifacts-windows-x64
