name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Artifacts
      run: make artifacts

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts-linux-x64/,artifacts-windows-x64/,artifacts-arm-x64/"
        token: ${{ secrets.GITHUB_TOKEN }}
