name: Releases

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: install multilibs
      run: sudo apt-get install gcc-multilib gcc-mingw-w64

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build Artifacts
      run: |
        make artifacts
        zip -9r artifacts-linux-x64.zip artifacts-linux-x64/*
        zip -9r artifacts-windows-x64.zip artifacts-windows-x64/*
        zip -9r artifacts-arm-x64.zip artifacts-arm-x64/*

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "artifacts-linux-x64.zip,artifacts-windows-x64.zip,artifacts-arm-x64.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
